secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - /home/hporta-c/data/mysql:/var/lib/mysql
    networks:
      - inception

  # wordpress:
  #   build: ./requirements/wordpress
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - MYSQL_HOST=mariadb
  #     - MYSQL_USER=wp_user
  #     - MYSQL_PASSWORD_FILE=/run/secrets/db_password
  #     - MYSQL_DATABASE=wordpress
  #   secrets:
  #     - db_password
  #   volumes:
  #     - /home/hporta-c/data/wordpress:/var/www/html
  #   networks:
  #     - inception

  # nginx:
  #   build: ./requirements/nginx
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - 443:443
  #   networks:
  #     - inception

networks:
    inception:
      name: inception
      driver: bridge
